/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Destination } from "./types";

export const CURATED_DESTINATIONS: Destination[] = [
  // --- Category: mountains (Mountains & Hills) ---
  {
    id: "srinagar-kashmir",
    name: "Srinagar & Kashmir Valley",
    country: "India",
    category: "mountains",
    image: "/images/destinations/srinagar-kashmir.jpg",
    description: "Known as 'Paradise on Earth', experience breathtaking alpine meadows, houseboats on serene Dal Lake, and Shalimar Mughal Gardens.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 18500,
    highlights: ["Dal Lake Shikara Ride", "Shalimar Mughal Gardens", "Hazratbal Shrine", "Nishat Bagh Springs"],
    bestTime: "April to October",
    locations: ["Srinagar Central", "Dal Lake Houseboats", "Nishat & Shalimar Gardens", "Chashme Shahi Springs", "Shankaracharya Hill"],
    longSummary: "Discover the spectacular charm of the summer capital. Wake up to misty mornings on wooden shikaras, tour historic Mughal terraces, and sample robust local cuisine in Srinagar."
  },
  {
    id: "gulmarg-snow",
    name: "Gulmarg Alpine Escape",
    country: "India",
    category: "mountains",
    image: "/images/destinations/gulmarg-snow.jpg",
    description: "Witness pure white paradise with Asia's highest cable car systems, snow glades, and golf meadows.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 15900,
    highlights: ["Gulmarg Gondola Ride", "Apharwat Peak Snow Sports", "Outer Circle Walk", "St. Mary's Wooden Church"],
    bestTime: "December to March (Snow), June to Sept (Lush Green)",
    locations: ["Gulmarg meadow core", "Apharwat peak station 1 & 2", "Strawberry Valley", "Khilanmarg alpine meadow", "Baba Reshi shrine"],
    longSummary: "Settle into majestic high snow slopes. Traverse evergreen pine forests on the standard Gondola and enjoy pristine views of Nanga Parbat on this thrilling alpine experience."
  },
  {
    id: "leh-ladakh",
    name: "Leh & Ladakh Extreme",
    country: "India",
    category: "mountains",
    image: "/images/destinations/leh-ladakh.jpg",
    description: "A high-altitude mountain wonderland studded with deep blue high passes, ancient cliffside monasteries, and the magnificent Pangong Tso Lake.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 23500,
    highlights: ["Pangong Tso Alpine Lake", "Khardung La High Pass", "Thiksey Monastery Solitude", "Magnetic Hill Experience"],
    bestTime: "June to September",
    locations: ["Leh Palace & Shanti Stupa", "Nubra Valley (Hunder Dunes, Double-hump camel rides)", "Pangong Tso Lake (High Altitudes)", "Khardung La Pass (5,359 meters)", "Diskit Monastery"],
    longSummary: "Prepare for an extraordinary excursion into the cold desert landscape of Ladakh. Drive up high-elevation roads like Khardung La, meet friendly Bactrian camels on the sands of Nubra, and spend the night in luxury yurts beside the brilliant blue shores of Pangong Lake on the Indo-Tibetan border."
  },
  {
    id: "manali-escapade",
    name: "Manali Alpine Sanctuary",
    country: "India",
    category: "mountains",
    image: "/images/destinations/manali-escapade.jpg",
    description: "High adventure and snowy valleys. Try paragliding in Solang, scale the Atal Tunnel, hike to peaceful old wooden temples, and breathe pure deodar-scented air.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 11500,
    highlights: ["Solang Valley Paragliding", "Rohtang Pass Snow Sports", "Atal Tunnel Expedition", "Hadimba Temple Forest Walk"],
    bestTime: "October to June",
    locations: ["Hadimba Pine Forest Temple", "Solang Valley Adventure Hub", "Rohtang Pass glaciers", "Atal Tunnel & Sissu Keylong Valleys", "Old Manali wooden cafes"],
    longSummary: "Manali blends soaring alpine scenery with endless outdoor opportunities. Travel through the revolutionary Atal Tunnel to feel the dry, Tibetan winds of Lahaul, trek to cascading Jogini falls, and walk beneath high deodar trees to the historic Hadimba Temple."
  },
  {
    id: "shimla-queen",
    name: "Shimla Colonial Retreat",
    country: "India",
    category: "mountains",
    image: "/images/destinations/shimla-queen.jpg",
    description: "The summer capital of British India. Walk the traffic-free Mall Road, ride the UNESCO toy train, and watch the orange sun set over endless pine-covered ridges.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 10900,
    highlights: ["UNESCO Kalka-Shimla Toy Train", "The Ridge pedestrian walks", "Viceregal Lodge heritage tour", "Jakhoo Temple hilltop vistas"],
    bestTime: "March to June, November to February",
    locations: ["The Ridge & Mall Road", "Jakhu Hill (Lord Hanuman giant icon)", "Viceregal Lodge (Neo-gothic architecture)", "Kufri (Himalayan Nature Park)", "Chail Palace"],
    longSummary: "Step back into the charm of bygone eras in Shimla, the legendary 'Queen of Hills'. Settle into structural heritage cottages, enjoy a romantic nostalgic ride on the UNESCO World Heritage toy train winding through deep mountain tunnels, and stroll the lively Ridge without any motor traffic."
  },
  {
    id: "dharamshala-hills",
    name: "Dharamshala & McLeodGanj",
    country: "India",
    category: "mountains",
    image: "/images/destinations/dharamshala-hills.jpg",
    description: "Home of His Holiness The Dalai Lama. Walk through cedar forests, beautiful organic tea estates, and active Tibetan monasteries.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 9900,
    highlights: ["Tsuglagkhang Dalai Lama temple", "Bhagsunag cold waterfalls", "Kangra Fort ruins", "St. John Wilderness church"],
    bestTime: "September to June",
    locations: ["Lower Dharamshala markets", "McLeodGanj main square", "Dharamkot backpackers hill", "Bhagsunag temple", "Naddi sunset point"],
    longSummary: "Breathe in quiet Himalayan spirituality in McLeodGanj. Listen to debating monks, spin prayer wheels, hike to beautiful pine viewpoints, and sip steaming butter chai in quiet cliff cafes."
  },
  {
    id: "nainital-lakes",
    name: "Nainital Lake District",
    country: "India",
    category: "mountains",
    image: "/images/destinations/nainital-lakes.jpg",
    description: "Settle beside shimmering emerald volcanic lakes, sail peacefully in wooden rowboats, and enjoy epic panoramas of the gigantic Nanda Devi peaks.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 9500,
    highlights: ["Naini Lake Yachting", "Snow View Cable Car Ascent", "Mall Road Lakeside Walks", "Bhimtal & Sattal Lake Tours"],
    bestTime: "March to June, September to November",
    locations: ["Naini Lake & Yacht Club", "Naina Devi Temple", "Tiffin Top (Khurpatal vistas)", "Bhimtal & Naukuchiatal active sports hubs", "Eco Cave Gardens"],
    longSummary: "Escape to Kumaon's beloved lake destination. Unwind with early morning wooden boating on Lake Naini, take an aerial cable car ride up to watch snow peaks, and explore nearby lesser-known lakes Bhimtal and Sattal."
  },
  {
    id: "mussoorie-mist",
    name: "Mussoorie Mist Escape",
    country: "India",
    category: "mountains",
    image: "/images/destinations/mussoorie-mist.jpg",
    description: "The 'Queen of the Hills' in Uttarakhand. Witness stunning views of Doon Valley, cascade pools, and classic colonial structures.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 8900,
    highlights: ["Kempty Falls waterfall hike", "Lal Tibba vintage telescope point", "Gun Hill cable cars", "Mall Road pedestrian walk"],
    bestTime: "March to June, Oct to Dec",
    locations: ["Mussoorie Mall Road", "Lal Tibba peak", "Kempty cascading waterfalls", "Cloud's End forest perimeter", "Company Garden"],
    longSummary: "Walk along the misty ridges of Mussoorie. Watch the distant golden sunset over the snow-capped Himalayan peaks, visit classic colonial mansions, and explore pine paths near famous author Ruskin Bond's quiet home."
  },
  {
    id: "auli-ski",
    name: "Auli Ski & Snowy Meadows",
    country: "India",
    category: "mountains",
    image: "/images/destinations/auli-ski.jpg",
    description: "India's premier skiing destination, offering pristine powdery slopes and towering views of Nanda Devi peak.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 14500,
    highlights: ["Skiing on powdery slopes", "Auli Ropeway scenic ride", "Gorson Bugyal high meadow trek", "Artificial high mountain lake"],
    bestTime: "December to March (For Skiing), May to Sept (Lush Green Bugyals)",
    locations: ["Joshimath Gateway base", "Auli main ski slopes", "Gorson Bugyal high-altitude meadows", "Chattrakund forest lake"],
    longSummary: "Ski through the world-class snow-covered slopes of Auli. Framed by majestic peaks like Nanda Devi, Hathi Parbat, and Trishul, this highland ski paradise offers absolute serenity and beautiful pine treks."
  },
  {
    id: "gangtok-hills",
    name: "Gangtok Himalayan Silk Road",
    country: "India",
    category: "mountains",
    image: "/images/destinations/gangtok-hills.jpg",
    description: "Explore clean, green Buddhist hills, serene high altitude Lakes on the Chinese border, and breathtaking vistas of Mount Kanchenjunga.",
    rating: 4.8,
    priceLevel: "$$$",
    startPrice: 12900,
    highlights: ["Tsomgo Sacred Lake", "Rumtek Monastery chanting", "Nathu La Pass Border Gateway", "MG Marg clean market walk"],
    bestTime: "March to June, October to December",
    locations: ["Gangtok MG Marg pedestrian lane", "Tsomgo High Altitude Glacial Lake (3,753 meters)", "Nathu La Pass border gate", "Rumtek monastery", "Banjhakri waterfalls"],
    longSummary: "Tour the beautiful organic state of Sikkim. Discover peaceful monasteries, stand beside the high-altitude frozen Tsomgo Lake, and drive through challenging mountain curves on standard border checkpaths."
  },
  {
    id: "darjeeling-hills",
    name: "Darjeeling Tea & Vistas",
    country: "India",
    category: "mountains",
    image: "/images/destinations/darjeeling-hills.jpg",
    description: "Wake up to stunning views of Mt. Kanchenjunga, tour fragrant, mist-shrouded green tea plantations, and ride the classic vintage steam Toy Train.",
    rating: 4.8,
    priceLevel: "$$$",
    startPrice: 13900,
    highlights: ["Tiger Hill Sunrise peak views", "UNESCO steam Toy Train", "Happy Valley Tea Estate tea testing", "Ghoom Monastery chants"],
    bestTime: "March to May, September to November",
    locations: ["Tiger Hill peak view point", "Batasia Loop & War Memorial", "Happy Valley Tea Estate", "Ghoom Monastery & Peace Pagoda", "Himalayan Mountaineering Institute"],
    longSummary: "Perched high on mountain ridges, Darjeeling is legendary for its fine tea gardens and breathtaking sunrises over Mount Kanchenjunga (the world's third highest peak). Wake up before dawn to see the first gold sun rays illuminate the snowy mountain peaks on this high mountain odyssey."
  },
  {
    id: "shillong-meghalaya",
    name: "Shillong & Meghalaya Hills",
    country: "India",
    category: "mountains",
    image: "/images/destinations/shillong-meghalaya.jpg",
    description: "Visit the 'Scotland of the East'. Discover sacred root bridges, emerald mist-filled valleys, and cleanest Asian villages.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 11900,
    highlights: ["Living Root Bridges of Mawlynnong", "Umiam turquoise lake boating", "Cherrapunji wet waterfall trails", "Elephant Falls rock steps"],
    bestTime: "September to May",
    locations: ["Shillong Ward's Lake park", "Cherrapunji (Mawsmai caves, Nohkalikai)", "Mawlynnong cleanest village", "Shillong Peak overlook", "Dawki crystal boating"],
    longSummary: "Encounter nature's spectacular wonders in Meghalaya. Walk across roots trained by Khasi tribes to cross roaring rivers, sail in boats that float over crystal glass-like water in Dawki, and explore damp prehistoric cave pathways."
  },

  // --- Category: beaches (Beaches & Coasts) ---
  {
    id: "goa-beaches",
    name: "Sun-drenched Goa",
    country: "India",
    category: "beaches",
    image: "/images/destinations/goa-beaches.jpg",
    description: "From wild waves to quiet white-sand escapes. Discover Portuguese baroque architectural roots, legendary beach shacks, and tropical spice farms.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 9900,
    highlights: ["Palolem Beach Relaxing", "Basilica of Bom Jesus", "Fontainhas Latin Quarter", "Dudhsagar Waterfall Trek"],
    bestTime: "November to February",
    locations: ["Fontainhas Latin Quarter", "Old Goa Churches (Basilica of Bom Jesus)", "Palolem & Agonda Beaches (South)", "Mondrem & Arambol (North)", "Sahakari Spice Farm"],
    longSummary: "Discover the twin souls of Goa: the Portuguese-influenced heritage architecture and the sun-soaked coastlines. Walk through the colorful, pastel-toned streets of Fontainhas, gaze at standard-setting colonial cathedrals, and trek through lush spice plantations."
  },
  {
    id: "gokarna-beaches",
    name: "Gokarna Serene Shores",
    country: "India",
    category: "beaches",
    image: "/images/destinations/gokarna-beaches.jpg",
    description: "Experience untouched coastlines and peaceful shorelines where sacred temple culture meets the rocky cliffs of the Arabian sea.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 8500,
    highlights: ["Om Beach sunset cliff trek", "Half Moon beach hideout", "Mahabaleshwar historic Shiva shrine", "Kudle Beach shack dinners"],
    bestTime: "October to March",
    locations: ["Gokarna Temple core", "Kudle rocky beach border", "Om Beach outline", "Paradise beach cove", "Mirjan Fort heritage wall"],
    longSummary: "Gokarna offers a restful alternative to busy holiday crowds. Trek over dramatic headlands connecting coastal coves, swim in quiet blue bays shape like the holy syllable 'Om', and experience historic sandstone temple architecture."
  },
  {
    id: "pondicherry-french",
    name: "Pondicherry French Quarter",
    country: "India",
    category: "beaches",
    image: "/images/destinations/pondicherry-french.jpg",
    description: "Delight in mustard-painted French colonial lanes, cycle past bougainvillea arches, and visit the serene Auroville township.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 9200,
    highlights: ["Auroville Globe Matrimandir tour", "Promenade Beach sunset walks", "White Town heritage bicycle ride", "French pastries gourmet sampling"],
    bestTime: "October to March",
    locations: ["White Town French Colony", "Auroville global community township", "Paradise beach private ferry route", "Sri Aurobindo Ashram", "Goubert Avenue seafront Promenade"],
    longSummary: "Immerse yourself in India's unique French community enclave. Pondicherry features beautiful architecture, tranquil sandy coastlines, and a serene community at Auroville dedicated to absolute harmony."
  },
  {
    id: "varkala-cliff",
    name: "Varkala Cliffside Coast",
    country: "India",
    category: "beaches",
    image: "/images/destinations/varkala-cliff.jpg",
    description: "Perched above the Arabian sea, Varkala features unique red laterite cliffs, paragliding adventures, and historic natural springs.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 8800,
    highlights: ["Red Cliff Cafe strolling", "Papanasam holy shoreline dips", "Paragliding over rocky coast", "Anjengo Fort colonial history"],
    bestTime: "September to March",
    locations: ["Varkala Cliff seaside market", "Papanasam sacred beach", "Janardhana Swamy ancient temple", "Kapil Lake backwater connection", "Anjengo lighthouse and fort"],
    longSummary: "Relax to the soothing sound of waves crashing against stunning red cliffs. Varkala is acclaimed for its clifftop bohemian cafes, pristine beaches, and ancient mineral hot springs that bubble beside the ocean."
  },
  {
    id: "kovalam-beach",
    name: "Kovalam Golden Sands",
    country: "India",
    category: "beaches",
    image: "/images/destinations/kovalam-beach.jpg",
    description: "Famous for its stripe-painted high Lighthouse, Kovalam offers three crescent-shaped beaches perfect for water sports and heritage spa therapies.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 10200,
    highlights: ["Lighthouse Hill panorama", "Hawah Beach surfing and catamarans", "Ayurvedic rejuvenating massage treatments", "Karamana River boating"],
    bestTime: "September to March",
    locations: ["Lighthouse Beach crescent", "Hawah fishermen beach", "Samudra quiet shorelines", "Halcyon Castle estate", "Vellayani fresh lake"],
    longSummary: "Kovalam has been India's top beach retreat since the hippie era. Stroll beneath massive palm groves, scale the spiral steps of the iconic red-and-white lighthouse, and indulge in standard-setting traditional massage therapies."
  },
  {
    id: "alleppey-boat",
    name: "Alleppey Houseboat Backwaters",
    country: "India",
    category: "beaches",
    image: "/images/destinations/alleppey-boat.jpg",
    description: "The 'Venice of the East'. Settle into wood-carved traditional houseboats floating through palm-shaded canals, lagoon networks, and tasty seafood shacks.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 14900,
    highlights: ["Overnight stay in Kettuvallam boat", "Vembanad Lake wide cruise", "Paddy field canal walks", "Kumarakom Bird Sanctuary visits"],
    bestTime: "September to March",
    locations: ["Alleppey Finish Point jetty", "Punnamada Lake racing trail", "Vembanad wide lagoons", "Pathiramanal secret island", "Marari serene white-sand beach"],
    longSummary: "Settle into slow backwater living with this luxury tour. Watch rural Kuttanad life go by as your personal chef preps fresh fish and traditional curries onboard your custom premium wooden houseboat."
  },
  {
    id: "andaman-islands",
    name: "Andaman & Nicobar Paradise",
    country: "India",
    category: "beaches",
    image: "/images/destinations/andaman-islands.jpg",
    description: "Escape to Havelock and Neil islands. Swim over coral reefs, dive into turquoise waters, and visit Radhanagar (Asia's premier beach).",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 21900,
    highlights: ["Radhanagar white sand lounging", "Havelock scuba & vibrant coral reef", "Cellular Jail national memorial tour", "Neil Island natural rock arches"],
    bestTime: "October to May",
    locations: ["Port Blair historic jail", "Havelock Island (Radhanagar, Elephant beach)", "Neil Island (Bharatpur, Laxmanpur)", "Baratang mangrove river canals", "Ross Island ruins"],
    longSummary: "Journey to deep tropical waters of India. Dive amongst colorful schools of fish, stroll the flawless fine sands of Havelock, and learn historic colonial legacies at standard heritage memorials."
  },
  {
    id: "lakshadweep-atoll",
    name: "Lakshadweep Coral Atolls",
    country: "India",
    category: "beaches",
    image: "/images/destinations/lakshadweep-atoll.jpg",
    description: "Step onto untouched turquoise coral lagoons, snorkel with sea turtles, and relax in eco-luxury beach villas.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 24500,
    highlights: ["Lagoon snorkeling with sea turtles", "Deep sea kayaking in coral waters", "Agatti reef dive centers", "Bangaram untouched sandbank walk"],
    bestTime: "October to Mid-May",
    locations: ["Agatti island airstrip and lagoon", "Bangaram uninhabited lagoon ring", "Kavaratti administrative marine center", "Kalpeni coral storm banks", "Kadmat water sports hub"],
    longSummary: "Settle into standard-setting isolation off India's west coast. Wander white coral atolls ringed by translucent green lagoons, watch diverse reef sharks, and explore standard marine biosphere islands."
  },

  // --- Category: culture (Heritage & Royal Cities) ---
  {
    id: "jaipur-heritage",
    name: "Jaipur Pink Heritage",
    country: "India",
    category: "culture",
    image: "/images/destinations/jaipur-heritage.jpg",
    description: "Witness massive fortress gates, block printing, and the stunning pink facade of Hawa Mahal in Rajasthan's Royal capital.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 8900,
    highlights: ["Amer Fort wall mirrors", "Hawa Mahal facade walk", "Jantar Mantar cosmic dial", "City Palace courtyard rooms"],
    bestTime: "October to March",
    locations: ["Jaipur Pink City wall", "Amer hill fort", "City Palace Royal museum", "Albert Hall museum", "Galta Ji monkey temple"],
    longSummary: "Jaipur is a marvelous showcase of traditional architecture and regal living. Experience standard luxury heritage stays, witness elephant gate guards, and explore ancient gemstone bazaars."
  },
  {
    id: "udaipur-lake",
    name: "Udaipur Romantic Lakes",
    country: "India",
    category: "culture",
    image: "/images/destinations/udaipur-lake.jpg",
    description: "The 'Venice of the East'. Experience romantic lakeside forts, majestic white palaces reflecting on Lake Pichola, and standard royal gardens.",
    rating: 4.8,
    priceLevel: "$$$",
    startPrice: 11500,
    highlights: ["Lake Pichola sunset boat ride", "City Palace massive courtyards", "Jag Mandir Island palace", "Saheliyon-ki-Bari fountains"],
    bestTime: "October to March",
    locations: ["Lake Pichola waterfront ghats", "Udaipur City Palace complex", "Sajjangarh high forest Monsoon palace", "Fateh Sagar lake parks", "Bagore ki Haveli folk center"],
    longSummary: "Discover the standard-setting romantic city of India. Enjoy elegant sunset boat cruises alongside floating white palaces, browse miniature heritage paintings, and listen to authentic folk sitar concerts."
  },
  {
    id: "jodhpur-blue",
    name: "Jodhpur Royal Blue City",
    country: "India",
    category: "culture",
    image: "/images/destinations/jodhpur-blue.jpg",
    description: "Scale the massive defensive Mehrangarh Fort towering above an endless landscape of beautiful blue Brahmin houses.",
    rating: 4.8,
    priceLevel: "$$$",
    startPrice: 9800,
    highlights: ["Mehrangarh Fort golden ramparts", "Jaswant Thada white cenotaphs", "Blue Quarter guided photography walks", "Umaid Bhawan palace museum"],
    bestTime: "October to March",
    locations: ["Mehrangarh rock cliff base", "Navchokiya absolute blue lanes", "Jaswant Thada gardens", "Clock tower Spice bazaars", "Mandore garden ruins"],
    longSummary: "Gaze over the sun-drenched Blue City from one of India's most standard fortress ramparts. Walk through blue alleys, talk with local craft weavers, and feast on Rajasthani Mirchi Bada at the busy Clock Tower bazaar."
  },
  {
    id: "jaisalmer-golden",
    name: "Jaisalmer Desert Oasis",
    country: "India",
    category: "culture",
    image: "/images/destinations/jaisalmer-golden.jpg",
    description: "The Golden City of Thar. Stay in desert camps, ride camels over rolling sand dunes, hear local musical legends, and explore the living Jaisalmer Fort.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 11900,
    highlights: ["Sam Sand Dunes Desert luxury tents", "Camel Camel safari sunset", "Jaisalmer Golden Fort walk", "Patwon ki Haveli stone carvings"],
    bestTime: "October to March",
    locations: ["Jaisalmer Fort (Sonar Qila)", "Sam Sand Dunes (Thar desert boundary)", "Patwon ki Haveli & Salim Singh Haveli", "Gadisar Lake rowboats", "Kuldhara Ghost Village tour"],
    longSummary: "Escape to the beautiful desert sands of the Thar on this premium Arabian-style getaway. Walk inside the massive fort maze where generations have lived for 800 years, ride a camel straight into a gorgeous desert sunset, and watch spectacular Rajasthani performances."
  },
  {
    id: "agra-taj",
    name: "Agra & The Taj Mahal",
    country: "India",
    category: "culture",
    image: "/images/destinations/agra-taj.jpg",
    description: "Stand before the ultimate monument of love. Gaze over Agra's red palaces, Mughal gardens, and delicate marble inlays.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 4900,
    highlights: ["Taj Mahal sunrise entry", "Agra Fort massive red sandstone chambers", "Itmad-ud-Daulah (Baby Taj) marble carvings", "Fatehpur Sikri ghost city gate"],
    bestTime: "October to March",
    locations: ["Taj Mahal riverside grounds", "Agra Fort royal chambers", "Mehtab Bagh moonlit sunset view", "Sikandra Akbar tomb park", "Fatehpur Sikri historic court"],
    longSummary: "Nothing compares to seeing the Taj Mahal catch the first pink rays of dawn. Walk ancient courtyards of the grand Mughal empire, purchase fine marble souvenirs, and learn incredible stories of standard royalty."
  },
  {
    id: "varanasi-spirit",
    name: "Spiritual Varanasi",
    country: "India",
    category: "culture",
    image: "/images/destinations/varanasi-spirit.jpg",
    description: "One of the oldest continuously inhabited cities on earth. Connect with deep spirituality along the sacred Ganga Ghats, ancient shrines and Ganga Aarti rituals.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 7900,
    highlights: ["Ganga Sunrise Boat Ride", "Dasaswamedh Ghat Aarti", "Kashi Vishwanath Temple", "Sarnath Buddhist Stupa Walk"],
    bestTime: "October to March",
    locations: ["Varanasi Ghats (Dashashwamedh, Assi)", "Kashi Vishwanath Corridor", "Sarnath (Dhamek Stupa, Deer Park)", "Banaras Hindu University campus"],
    longSummary: "Unearth the deep, mystical heritage of India in sacred Banaras. Float on the holy River Ganges at sunrise to witness age-old morning physical and spiritual traditions, stand in awe as oil lamps illuminate Dashashwamedh Ghat during evening Ganga Aarti."
  },
  {
    id: "khajuraho-culture",
    name: "Khajuraho Stone Temples",
    country: "India",
    category: "culture",
    image: "/images/destinations/khajuraho-culture.jpg",
    description: "Explore the UNESCO-listed Chandela temples adorned with detailed stone carvings, sculptures, and architectural formations.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 7500,
    highlights: ["Kandariya Mahadeva stone carvings", "Light and Sound spectacular evening show", "Adinath peaceful Jain temples", "Raneh canyon waterfalls"],
    bestTime: "October to March",
    locations: ["Western Group of Temples", "Eastern Group Jain temples", "Archaeological gold museum", "Raneh Waterfalls granite cliffs", "Panna Tiger reserve nearby"],
    longSummary: "Delve into the pinnacle of ancient stone craftsmanship. The massive temples of Khajuraho present standard-setting expressions of life, philosophy, and classical art sculpted into sandstone."
  },
  {
    id: "hampi-ruins",
    name: "Hampi Ruins of Vijayanagara",
    country: "India",
    category: "culture",
    image: "/images/destinations/hampi-ruins.jpg",
    description: "Discover a dreamlike landscape of ancient stone boulders, royal temple columns, and classic stone chariots beside the Tungabhadra river.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 8900,
    highlights: ["Stone Chariot at Vittala temple", "Virupaksha soaring gopuram gate", "Lotus Mahal royal pavilion", "Tungabhadra river bowl-boat ride"],
    bestTime: "October to March",
    locations: ["Hampi Bazaar historical ruins", "Vittala temple music columns", "Royal Enclosure platforms", "Hemakuta hill viewpoints", "Anegundi primitive settlement"],
    longSummary: "Explore the ruins of the spectacular medieval Indian empire of Vijayanagara. Wander amongst boulder-strewn hills, step inside grand columned palaces, and ride coracles across the scenic Tungabhadra."
  },
  {
    id: "mysore-palace",
    name: "Mysore Palace & Royal Heritage",
    country: "India",
    category: "culture",
    image: "/images/destinations/mysore-palace.jpg",
    description: "Gaze at the massive Maharaja Palace illuminated by 100,000 electric bulbs, buy pure sandalwood, and tour the Chamundi hills.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 6900,
    highlights: ["Maharaja's Palace light show", "Chamundeshwari hilltop temple steps", "Devaraja heritage market strolls", "Brindavan musical fountain gardens"],
    bestTime: "October to March",
    locations: ["Mysore Palace royal chambers", "Chamundi Hill overlook", "Devaraja vegetable and spice stalls", "Srirangapatna historical island", "Somnathpur intricate temple carvings"],
    longSummary: " Mysore captures classic Karnataka heritage perfectly. Buy legendary royal silks, stroll down avenues lined with standard imperial arches, and photograph the world-famous illuminated Palace."
  },
  {
    id: "hyderabad-city",
    name: "Hyderabad Nizam & Pearls",
    country: "India",
    category: "culture",
    image: "/images/destinations/hyderabad-city.jpg",
    description: "Taste authentic Biryani, wander the four arches of Charminar, and buy delicate Gulf pearls and lac bangles.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 7900,
    highlights: ["Charminar central minarets", "Golconda Fort sound echo walls", "Chowmahalla Palace chandeliers", "Nizam's rich mutton biryani"],
    bestTime: "September to March",
    locations: ["Charminar historical square", "Golconda fort ramparts", "Chowmahalla Palace gardens", "Laad Bazaar bangle lane", "Salar Jung antique museum"],
    longSummary: "Experience the standard royal grandeur of the Nizams. Hyderabad blends beautiful Islamic archway structures with high technology, world-famous spice markets, and majestic fort ruins."
  },
  {
    id: "amritsar-golden",
    name: "Amritsar Holy Golden Temple",
    country: "India",
    category: "culture",
    image: "/images/destinations/amritsar-golden.jpg",
    description: "Peacefully bow at the grand Harmandir Sahib (Golden Temple), share standard langar meals, and witness the Wagah Border parade.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 5900,
    highlights: ["Harmandir Sahib gold reflection", "Langar community mega kitchen service", "Wagah Border national defense parade", "Jallianwala Bagh Martyr memorials"],
    bestTime: "October to March",
    locations: ["Golden Temple central lake complex", "Jallianwala Bagh gardens", "Wagah border Stadium area", "Amritsar colonial heritage street", "Gobindgarh fort legacy displays"],
    longSummary: "Feel deep humbleness and intense devotion at Punjab's sacred city. Cooperate in the world's largest free mega-kitchen, watch standard-setting cross-border guard handshakes, and sample classic butter-laced Kulchas."
  },
  {
    id: "lucknow-city",
    name: "Lucknow Nawabs & Awadh",
    country: "India",
    category: "culture",
    image: "/images/destinations/lucknow-city.jpg",
    description: "Explore the acoustic wonders of Bara Imambara, admire Chikankari hand-embroidery, and sample Awadhi Mughlai culinary delicacies.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 6500,
    highlights: ["Bara Imambara acoustic maze (Bhool Bhulaiya)", "Rumi Darwaza imposing arch structure", "Hazratganj shopping districts", "Chikankari delicate threadwork markets"],
    bestTime: "October to March",
    locations: ["Bara Imambara", "Chhota Imambara", "Rumi Darwaza gateway", "British Residency ruins", "Aminabad traditional street markets"],
    longSummary: "Enjoy the refined language, polite manners, and incredible Awadhi cuisine of Lucknow. Explore a massive labyrinth built without any pillars, see skilled cotton tailors working, and satisfy your cravings with melt-in-the-mouth kebabs."
  },

  // --- Category: nature (Nature & Wildlife) ---
  {
    id: "jim-corbett",
    name: "Jim Corbett Jungle Trails",
    country: "India",
    category: "nature",
    image: "/images/destinations/jim-corbett.jpg",
    description: "India's oldest national tiger reserve. Experience 4x4 open-jeep rides beside the Ramganga river, tracking wild tigers and elephants.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 7900,
    highlights: ["Dhikala deep zone jeep safari", "Wild tiger and elephant tracking", "Ramganga river bridge sunsets", "Garjiya Temple rock walks"],
    bestTime: "November to June",
    locations: ["Ramnagar central reception", "Dhikala deep wilderness ranges", "Bijrani grasslands path", "Jhirna forest habitat zone", "Corbett Museum heritage house"],
    longSummary: "Enter the world of the Royal Bengal Tiger under Uttarakhand's green heights. Settle into wild riverside forest lodges, sleep near roaring Ramganga rivers, and take morning safaris through golden Sal meadows."
  },
  {
    id: "ranthambore-safari",
    name: "Ranthambore Royal Tiger Safari",
    country: "India",
    category: "nature",
    image: "/images/destinations/ranthambore-safari.jpg",
    description: "Witness Bengal Tigers slinking past medieval ruins, ancient banyan trees, and majestic fortress walls in Rajasthan.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 8500,
    highlights: ["Fort-side tiger spotting excursions", "Ranthambore Fortress clifftop view", "Padam Talao lake bird watching", "Open canter wildlife tours"],
    bestTime: "October to June",
    locations: ["Sawai Madhopur hub station", "Ranthambore dry deciduous forest limits", "Hills of Ranthambore high fort", "Padam Talao lake pavilion", "Jogi Mahal heritage bungalow"],
    longSummary: "Ranthambore is a rare intersection of deep forests and heritage forts. Track tigers resting near ancient lake pavilions, observe marsh crocodiles, and climb the thousand-year-old clifftop citadel."
  },
  {
    id: "kaziranga-rhino",
    name: "Kaziranga One-Horned Rhinos",
    country: "India",
    category: "nature",
    image: "/images/destinations/kaziranga-rhino.jpg",
    description: "Home to two-thirds of the world's great Indian one-horned rhinoceroses. Tour tall elephant-grass plains along the Brahmaputra.",
    rating: 4.9,
    priceLevel: "$$$",
    startPrice: 12500,
    highlights: ["Early morning swamp elephant ride", "Open jeep rhino photography sessions", "Brahmaputra boat river dolphin tours", "Orchid and tea estate walks"],
    bestTime: "November to April",
    locations: ["Kohora central forest section", "Bagori western rhino marshes", "Agaratoli woodlands area", "Brahmaputra river sandbanks", "Assam rustic tea gardens"],
    longSummary: "Venture into the wetlands of Assam. Meet majestic prehistoric-looking rhinos, observe wild water buffaloes, watch elegant swamp deer, and appreciate rare migratory water birds."
  },
  {
    id: "sundarbans-tiger",
    name: "Sundarbans Mangrove Trails",
    country: "India",
    category: "nature",
    image: "/images/destinations/sundarbans-tiger.jpg",
    description: "Sail through the world's largest coastal mangrove forest. Spot swimming tigers, estuary crocodiles, and unique wildlife on the Ganges delta.",
    rating: 4.7,
    priceLevel: "$$",
    startPrice: 6900,
    highlights: ["Sajnekhali watchtower sighting", "Narrow boat canal safari", "Mangrove interpretation tour", "Estuary crocodile spotting"],
    bestTime: "September to March",
    locations: ["Gadkhali local jetty gateway", "Sajnekhali tiger camp watchtower", "Sudhanyakhali deep range", "Dobanki canopy forest bridge", "Katka wildlife beach borders"],
    longSummary: "Sail down narrow, silent channels bordered by dense Sundari trees. Sundarbans is a complex world of tidal mudflats, elusive estuarine crocodiles, and rare swimming Bengal Tigers."
  },
  {
    id: "periyar-national",
    name: "Periyar Wildlife Sanctuary",
    country: "India",
    category: "nature",
    image: "/images/destinations/periyar-national.jpg",
    description: "A gorgeous lake reserve deep in the Western Ghats. Watch herds of wild elephants come down to drink, trek through organic spice woods, and bamboo raft.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 9800,
    highlights: ["Periyar Lake calm boat cruise", "Bamboo rafting on deep water", "Cardamom & pepper farm guided walks", "Sabarimala forest view points"],
    bestTime: "September to April",
    locations: ["Thekkady tourist center", "Periyar central lake basin", "Spice Route farm gardens", "Vandiperiyar highland tea zone", "Mangaladevi ancient forest shrine"],
    longSummary: "Breathe in spiced air in rubber and cardamom country. Boat alongside silent elephant herds resting on lake islets, spot Nilgiri langurs, and sleep in cozy wooden forest cottages."
  },
  {
    id: "coorg-coffee",
    name: "Coorg Coffee Highlands",
    country: "India",
    category: "nature",
    image: "/images/destinations/coorg-coffee.jpg",
    description: "Settle into the 'Scotland of India'. Hike beautiful coffee slopes, see elephants at Dubare camp, and visit Namdroling Golden Temple.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 10500,
    highlights: ["Abbey & Mallalli roaring waterfalls", "Dubare elephant scrubbing & river camp", "Golden Temple Bylakuppe Tibetan chants", "Coffee plantation guided estate walks"],
    bestTime: "October to April",
    locations: ["Madikeri central fortress town", "Bylakuppe serene Tibetan settlement", "Dubare riverbank camp", "Talakaveri sacred Cauvery spring", "Raja's Seat sunset garden overlook"],
    longSummary: "Stay in rustic plantation cottages in India's coffee land. Wake to the rich aroma of roasting robusta beans, shower in fresh forest waterfalls, and hear thousands of Buddhist monks chanting in the Golden Temple."
  },
  {
    id: "munnar-hills",
    name: "Munnar Tea hills",
    country: "India",
    category: "nature",
    image: "/images/destinations/munnar-hills.jpg",
    description: "Settle beside carpeted green hills, wild blue Neelakurinji slopes, and rare mountain Nilgiri Tahrs in Eravikulam National Park.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 9900,
    highlights: ["Eravikulam mountain Tahr spotting", "Mattupetty Lake echo points", "Tata tea processing museum", "Anamudi peak misty overlook"],
    bestTime: "September to May",
    locations: ["Munnar main tea valleys", "Eravikulam eco park summit", "Mattupetty concrete dam", "Kundala Lake yachting site", "Top Station valley view border"],
    longSummary: "Walk within massive geometric green tea lanes. Feel cool highland mist kiss your cheeks, look down over deep forest valleys from Anamudi Peak, and stay in rustic mountain huts."
  },
  {
    id: "spiti-valley",
    name: "Spiti Wilderness Expedition",
    country: "India",
    category: "nature",
    image: "/images/destinations/spiti-valley.jpg",
    description: "Experience the ultimate challenging cold desert pass, ancient Key Monastery, frozen valleys, and standard snow-covered cliffs.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 18900,
    highlights: ["Key Monastery cliffside halls", "Dhankar Castle hanging paths", "Chandra Taal high crescent-shaped lake", "Kaza highland marketplace"],
    bestTime: "June to September",
    locations: ["Kaza central Spiti valley", "Key Monastery rock walls", "Kibber high village settlement (4,270m)", "Hikkim (World's highest post office)", "Tabo old clay monastery (1000 years)"],
    longSummary: "Journey through rugged mountain passes into absolute, pristine isolation. Spiti Valley offers cold blue rivers, majestic cliff monasteries, fossils from prehistoric seas, and spectacular starry night skies."
  },

  // --- Category: historic (Spiritual & Cultural Destinations) ---
  {
    id: "rishikesh-yoga",
    name: "Rishikesh Yoga & Adventure",
    country: "India",
    category: "historic",
    image: "/images/destinations/rishikesh-yoga.jpg",
    description: "The global capital of Yoga meets the rushing waters of the Ganga. Experience high-octane white water rafting, riverside luxury camping, and cliff jumps.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 8900,
    highlights: ["Ganga River White-Water Rafting", "Beatles Ashram Graffitis", "Triveni Ghat Evening Aarti", "Laxman Jhula & Yoga Retreats"],
    bestTime: "September to November, February to May",
    locations: ["Laxman & Ram Jhula suspension bridges", "Beatles Ashram (Chaurasi Kutia)", "Shivpuri (Eco-camping, rafting hubs)", "Triveni Ghat (Ganga Arti)", "Neer Garh waterfalls"],
    longSummary: "Recharge your energy with a trip that combines spiritual tranquility and adrenaline-fueled adventures. Experience wild Grade III white-water rafting on the upper Ganges, camp on sandy riverbanks, and explore Beatles Ashram."
  },
  {
    id: "haridwar-spiritual",
    name: "Sacred Haridwar Gateway",
    country: "India",
    category: "historic",
    image: "/images/destinations/haridwar-spiritual.jpg",
    description: "Where the Ganges spills out into the great northern plains. Experience Har Ki Pauri ghat, temple cable-cars high above the city, and thousands of floating flower oil-lamps.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 6900,
    highlights: ["Har Ki Pauri Holy Dip", "Mansa Devi Ropeway Ascent", "Chandi Devi hilltop temple", "Bara Bazar religious market walk"],
    bestTime: "October to April",
    locations: ["Har Ki Pauri Ghat (Brahmakund)", "Mansa Devi Temple (Hilltop)", "Chandi Devi Temple", "Bharat Mata Mandir complex", "Daksh Mahadev historic shrine"],
    longSummary: "Witness India's spiritual pulse at Haridwar ('Gateway to the Gods'). Take a holy dip at the pristine Brahmakund, ascend via scenic ropeway cable cars to ancient temples high on the Shivalik hilltops."
  },
  {
    id: "bodh-gaya",
    name: "Bodh Gaya Lotus Meditation",
    country: "India",
    category: "historic",
    image: "/images/destinations/bodh-gaya.jpg",
    description: "Sit in silent meditation beneath the sacred Bodhi Tree where Prince Siddhartha attained supreme enlightenment.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 6500,
    highlights: ["Mahabodhi temple pyramidal spires", "Meditation beneath the Bodhi tree", "Vajrasana diamond throne", "International Buddhist monasteries"],
    bestTime: "October to March",
    locations: ["Mahabodhi Temple UNESCO site", "Great Buddha giant statue (25 meters)", "Royal Bhutan monastery", "Thai monastery gardens", "Falgu holy riverbanks"],
    longSummary: "Uncover deep inner peace at the world's most sacred Buddhist site. Meditate with orange-robed monks, wander gorgeous international monastery gardens, and sit beneath the direct descendant of the historic Bodhi tree."
  },
  {
    id: "puri-beach",
    name: "Puri Jagannath Coast",
    country: "India",
    category: "historic",
    image: "/images/destinations/puri-beach.jpg",
    description: "Bow before the legendary Lord Jagannath Temple, walk through golden sand temples, and explore the Konark Sun Temple chariot structures.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 7800,
    highlights: ["Jagannath sacred temple flags", "Konark Sun Temple stone chariot", "Puri beach sand art displays", "Chilika brackish lake dolphins"],
    bestTime: "October to March",
    locations: ["Puri Jagannath temple road", "Puri Sea beach boardwalk", "Konark Wheel heritage site", "Chilika Lake gateway (Satapada)", "Pipli local craft applique stalls"],
    longSummary: "Puri is a remarkable mix of ocean breezes and spiritual heritage. Stand before the giant, ancient Sun Temple chariot wheel carvings at Konark and watch fishermen boat past golden shorelines."
  },
  {
    id: "madurai-meenakshi",
    name: "Madurai Splendid Meenakshi",
    country: "India",
    category: "historic",
    image: "/images/destinations/madurai-meenakshi.jpg",
    description: "Behold the 14 soaring, colorful towers of the historic Meenakshi Amman Temple, adorned with thousands of carved mythological stone figures.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 6900,
    highlights: ["Aayiram Kaal Mandapam (1000 music pillars)", "Thirumalai Nayak Palace light displays", "Teppakulam massive temple tank", "Jigarthanda cold dairy treats"],
    bestTime: "October to March",
    locations: ["Meenakshi Amman ancient complex", "Thirumalai Nayakkar Mahal royal court", "Vandiyur Teppakulam lake temple", "Alagar Kovil scenic forest hill", "Gandhi historic memorial museum"],
    longSummary: "Madurai is the historic heart of Tamil Nadu. Marvel at the sheer scale of the Meenakshi temple's colorful gopurams, step inside the majestic arches of the Nayakkar Palace, and enjoy rich street food."
  },
  {
    id: "tirupati-temple",
    name: "Tirupati Balaji Darshan",
    country: "India",
    category: "historic",
    image: "/images/destinations/tirupati-temple.jpg",
    description: "Ascend the sacred Saptagiri (seven green hills) to worship at Tirumala, the world's most visited spiritual shrine.",
    rating: 4.9,
    priceLevel: "$$",
    startPrice: 5900,
    highlights: ["Tirumala sanctum gold dome", "Srivari laddu delicious prasadam", "Alipiri walking steps trail", "Kapila Theertham forest waterfalls"],
    bestTime: "September to March",
    locations: ["Tirumala hilltop shrine", "Sri Venkateswara central sanctuary", "Alipiri foot-paths route (3,500 stone steps)", "Kalyani forest dam", "Chandragiri historic fortress"],
    longSummary: "Experience standard-setting devotion at the sacred hill of Tirumala. Hear the continuous chants of 'Govinda', hike the scenic mountain stairs through deep forests, and visit ancient monuments."
  },
  {
    id: "ajmer-sharif",
    name: "Ajmer Sharif Sufi Peace",
    country: "India",
    category: "historic",
    image: "/images/destinations/ajmer-sharif.jpg",
    description: "Tie a sacred red thread at the holy tomb of Sufi saint Khwaja Moinuddin Chishti, and explore the beautiful Ana Sagar Lake.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 4900,
    highlights: ["Dargah Sharif marble dome", "Qawwali musical evening devotion", "Adhai Din Ka Jhonpra arches", "Ana Sagar lakeside sunset walks"],
    bestTime: "October to March",
    locations: ["Dargah Sharif central square", "Taragarh hill fort outlook", "Ana Sagar lake marble pavilions", "Nasiyan Jain golden temple", "Pushkar lakeside (nearby)"],
    longSummary: "Ajmer showcases the spiritual heart of Sufi mysticism in India. Sit in peaceful devotion listening to soaring Qawwali songs, stroll down old streets, and enjoy delicious local desserts."
  },
  {
    id: "kedarnath-temple",
    name: "Kedarnath Pilgrimage",
    country: "India",
    category: "historic",
    image: "/images/destinations/kedarnath-temple.jpg",
    description: "A gorgeous peak shrine nestled in the high Garhwal Himalayas. Hike alongside rushing rivers to reach the sacred old stone Shiva temple.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 15900,
    highlights: ["Kedarnath peak stone temple", "Scenic 16km mountain valley trek", "Evening bell pujas on mountain rivers", "Gaurikund natural hot spring"],
    bestTime: "May to June, September to October (Closed in Winters)",
    locations: ["Gaurikund trailhead gate", "Rambara resting camps", "Kedarnath high base valley (3,583 meters)", "Bhairav Temple alpine overlook", "Mandakini icy riverbanks"],
    longSummary: "Embark on an unforgettable pilgrimage into snow-capped Garhwal peaks. Join thousands of devotees chanting under towering glaciers, watch evening fire prayers, and find peace at this ancient sacred mountain sanctuary."
  },
  {
    id: "badrinath-temple",
    name: "Badrinath Sacred Shrine",
    country: "India",
    category: "historic",
    image: "/images/destinations/badrinath-temple.jpg",
    description: "Located between Nar and Narayan peaks, stand before the colorful Badrinath Temple on the banks of the roaring Alaknanda river.",
    rating: 4.9,
    priceLevel: "$$$$",
    startPrice: 14900,
    highlights: ["Colorful temple facade views", "Tapt Kund thermal sulfur springs", "Mana (the first Indian village on Tibet border)", "Vasudhara high mountain waterfalls"],
    bestTime: "May to June, Sept to October",
    locations: ["Tapt Kund river banks", "Badrinath Lord Vishnu temple core", "Mana Border community village", "Bheem Pul rocky gorge bridge", "Vyasa raw cave cells"],
    longSummary: "Encounter ancient Himalayan myths in Badrinath. Bathe in hot sulfur spring waters, walk to the Indo-Tibetan border village of Mana, and watch the rushing water of the Saraswati river disappear into rocky gorges."
  },
  {
    id: "dwarka-temple",
    name: "Dwarka Lord Krishna's Kingdom",
    country: "India",
    category: "historic",
    image: "/images/destinations/dwarka-temple.jpg",
    description: "Visit the legendary ancient beachfront capital of Lord Krishna, gaze over the Gomti river confluence, and cross the ocean to Bet Dwarka island.",
    rating: 4.8,
    priceLevel: "$$",
    startPrice: 9500,
    highlights: ["Dwarkadhish 5-story temple temple flag", "Sudama Setu suspension bridge walks", "Bet Dwarka sacred island boat ferry crossings", "Nageshwar majestic Jyotirlinga cave structure"],
    bestTime: "October to March",
    locations: ["Dwarkadhish central temple complex", "Gomti Ghat sacred riverbanks", "Rukmini Devi ancient shrine", "Bet Dwarka marine island", "Shivrajpur clean blue beach"],
    longSummary: "Step onto Gujarat's historic coastline. Gaze at the massive 5-story high temple of Dwarka, sail in traditional boats to offshore island temples, and watch the orange sun sink behind the Arabian sea."
  }
];

export const OTHER_RECOMMENDED_PROMPTS = [
  "A spiritual 5-day escape through Varanasi, Sarnath & Ayodhya",
  "A majestic 7-day desert camping and fort roadtrip in Jaisalmer & Jodhpur",
  "An adventurous 6-day wildlife safari and tea estate stroll in Munnar & Wayanad",
  "A royal 4-day heritage palace exploration in Pink City Jaipur"
];

export const WORLD_CLOCKS = [
  { city: "New Delhi", timezone: "Asia/Kolkata" },
  { city: "London", timezone: "Europe/London" },
  { city: "New York", timezone: "America/New_York" },
  { city: "Singapore", timezone: "Asia/Singapore" }
];

export const CURRENCY_LIST = [
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" }
];

export const MOCK_RATES: Record<string, number> = {
  "USD_INR": 83.50,
  "EUR_INR": 90.70,
  "GBP_INR": 105.80,
  "AED_INR": 22.70,
  "INR_USD": 0.012,
  "INR_EUR": 0.011,
  "INR_GBP": 0.0094,
  "INR_AED": 0.044,
};
